site_name: Form2Mail
site_description: Documentation Form2Mail Module
site_url: https://packagist.org/packages/yawik/form2mail
copyright: 'Copyright &copy; 2021'
repo_name: yawik/form2mail
repo_url: https://github.com/yawik/Form2Mail
site_dir: build/site
theme: material
markdown_extensions:
  - codehilite:
      guess_lang: true
  - toc:
      permalink: true
  - admonition
  - pymdownx.magiclink
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.extra
  - footnotes
