<?php

/**
 * AMS Form2Mail
 *
 * @copyright 2013-2021 CROSS Solution

 */

declare(strict_types=1);

use Laminas\Stdlib\ArrayUtils;

$width            = "600px";
$mail_blue_color  = "#7b1738";
$mail_white_color = "#fff";
$style_p          = "font-family: Arial, Helvetica, sans-serif; font-weight: 400; font-size: 15px; line-height: 1.8;";

?>
       <?= $this->partial('form2mail/mail/header', [
            'title' => $mail->getSubject(),
            'width'=>$width, 'mail_blue_color'=>$mail_blue_color,
            'mail_white_color' => $mail_white_color]); ?>
<h1>
    <?= $job ? 'Bewerbung auf ' . $job->getTitle() : 'Initiale Bewerbung'?>
</h1>
<h2>Kontaktdaten</h2>
<table class="data-display">
<tr><td>Anrede:</td><td><?=$user->getDisplayName(false)?></td></tr>
<tr><td>Anschrift:</td><td> <?=$user->getStreet()?> <?=$user->getHouseNumber()?><br>
                            <?=$user->getPostalCode()?> <?=$user->getCity()?></td></tr>
<tr><td>Telefon:</td><td><?=$user->getPhone()?></td></tr>
<tr><td>E-Mail:</td><td><?=$user->getEmail()?></td></tr>
</table>
<?php if (!empty($summary)): ?>
<h2>Anschreiben</h2>
<p>
    <?=$summary?>
</p>
<?php endif?>
<?php if (count($extras)): ?>
<h2>Weitere Angaben</h2>
<table class="data-display">
    <?php foreach ($extras as $key => $value):?>
    <tr><td><?=$key?></td>
    <td><?php
        if (is_array($value)):
            if (ArrayUtils::hasNumericKeys($values)):
                echo join(', ', $value);
            else:
                ?>
                <table class="data-display"><?php foreach ($value as $k => $v):?>
                    <tr><td><?=$k?></td><td><?=$v?></td></tr>
                <?php endforeach ?></table>
            <?php endif;
        else:
            echo $value;
        endif;
    ?></td></tr>
    <?php endforeach ?>
</table>
<?php endif?>

<?= $this->partial('form2mail/mail/footer', ['width' => $width, 'mail_white_color' => $mail_white_color, 'style' => $style_p]); ?>


