<?php

/**
 * AMS Form2Mail
 *
 * @copyright 2013-2021 CROSS Solution

 */

declare(strict_types=1);

?>
                                    <br>
                                    <p style="<?=$this->style?>">
                                        mit freundlichen Grüßen<br>
                                        HR-Team
                                    </p>
                                    <p style="<?=$this->style?>">
                                        DC Aviation GmbH<br>
                                        Stuttgart Airport<br>
                                        70629 Stuttgart, Germany<br>
                                        Phone +49 711 933 06-300<br>
                                        Fax +49 711 933 06-473<br>
                                        career@dc-aviation.com<br>
                                        www.dc-aviation.com
                                    </p>
                                    <p style="<?=$this->style?>">
                                        Managing Directors: Michael K. Kuhn (CEO), Marc Ambrosius (CFO)<br>
                                        Registergericht Stuttgart HRB 19256
                                    </p>
                                    <br>
                                    <p style="<?=$this->style?>">
                                        This e-mail may contain confidential and/or privileged information. If you are
                                        not the intended recipient (or have received this e-mail in error) please notify
                                        the sender immediately and destroy this e-mail. Any unauthorized copying,
                                        disclosure or distribution of the material in this e-mail is strictly forbidden.
                                    </p>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr><!-- end:tr -->
            </tr>
        </table>
    </div>
</center>
</body>
</html>
